name: release
on:
  push:
    branches: [main, "[0-9]*.[0-9]*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment:
      name: release
      url: https://pypi.org/project/mcward/
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: setup uv
        uses: astral-sh/setup-uv@v9.0.0

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: release python packages
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run tools/release.py python

      - name: release ward mod
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: uv run tools/release.py java
